/*
 MIT License
 Copyright (c) 2021 Lxc
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(b){var a=0;return function(){return a<b.length?{done:!1,value:b[a++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.makeIterator=function(b){var a="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return a?a.call(b):$jscomp.arrayIterator(b)};document.write("<script src='https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js'>\x3c/script>");
var aue={},aueMethod={},monitorTable=[],modelTable=[],Aue=function(b){try{this.el=b.el,this.data=b.data,this.methods=b.methods,Aue.init(this.data,this.methods),Aue.load(this.el)}catch(a){Aue.error(a.message)}};Aue.prototype.welcome=function(){var b=document.createElement("p");b.style.width="100%";b.style.textAlign="center";b.style.height="40px";var a=b.outerHTML;b.style.fontSize="25px";b.innerText="Welcome to Aue.js!";a+=b.outerHTML;$(this.el).html(a)};
Aue.init=function(b,a){for(var d in b)Aue.setMonitor(d),aue[d]=b[d];for(d in a)aueMethod[d]=a[d]};
Aue.loadEl=function(b){for(var a=b.firstChild;null!=a&&a!=b.lastChild;){if(1==a.nodeType)if(a.hasAttribute("a-for")){var d=a.getAttribute("a-for");a.removeAttribute("a-for");Aue.setFor($(a).prop("outerHTML"),a.parentElement,d,!0,a.hasAttribute("a-once"))}else null!==a.innerText.match(/{{(.+)}}/g)&&Aue.setInnerText(a,a.innerText,!0),a.hasAttribute("a-value")&&Aue.setValue(a,a.getAttribute("a-value"),!0),a.hasAttribute("a-model")&&Aue.setModel(a,a.getAttribute("a-model"),!0),a.hasAttribute("a-checked")&&
Aue.setChecked(a,a.getAttribute("a-checked"),!0),a.hasAttribute("a-show")&&Aue.setShow(a,a.getAttribute("a-show"),!0),a.hasAttribute("a-class")&&Aue.setClass(a,a.getAttribute("a-class"),!0),a.hasAttribute("a-click")&&Aue.setClick(a),a.removeAttribute("a-click"),a.removeAttribute("a-show"),a.removeAttribute("a-class"),a.removeAttribute("a-checked"),a.removeAttribute("a-value"),a.removeAttribute("a-model"),Aue.loadEl(a);a=a.nextSibling}};Aue.load=function(b){Aue.loadEl($(b).get(0))};
Aue.setInnerText=function(b,a,d){var c=a.substring(a.indexOf("{{")+2,a.lastIndexOf("}}"));if(void 0!==aue[$.trim(c)]){var e=void 0===aue[$.trim(c)]?a:aue[$.trim(c)];e=a.replace(new RegExp(c,"g"),e);e=e.replace(/{{/g,"");e=e.replace(/}}/g,"");b.innerText=e;d&&!b.hasAttribute("a-once")&&Aue.addMonitor(b,"innerText",{initialValue:a},$.trim(c))}};
Aue.setValue=function(b,a,d){var c=a.substring(a.indexOf("{{")+2,a.lastIndexOf("}}"));if(void 0===aue[$.trim(c)])b.value=a;else{var e=void 0===aue[$.trim(c)]?a:aue[$.trim(c)];e=a.replace(new RegExp(c,"g"),e);e=e.replace(/{{/g,"");e=e.replace(/}}/g,"");b.value=e;d&&!b.hasAttribute("a-once")&&Aue.addMonitor(b,"value",{initialValue:a},$.trim(c))}};
Aue.setModel=function(b,a,d){if(void 0!==aue[$.trim(a)]){var c=void 0===aue[$.trim(a)]?a:aue[$.trim(a)];c=a.replace(new RegExp(a,"g"),c);switch(b.type){case "checkbox":case "radio":b.checked="true"===c?!0:!1;d&&$(b).bind("change",function(e){aue[$.trim(a)]=$(this).is(":checked")});break;default:b.value=c,d&&$(b).bind("input propertychange",function(e){aue[$.trim(a)]=$(b).val()})}d&&Aue.addModel(b,"model",{variableName:a},$.trim(a))}};
Aue.setChecked=function(b,a,d){if(void 0!==aue[$.trim(a)]){var c=void 0===aue[$.trim(a)]?a:aue[$.trim(a)];b.checked=c;d&&!b.hasAttribute("a-once")&&Aue.addMonitor(b,"checked",{initialValue:a},$.trim(a))}};Aue.setShow=function(b,a,d){if(void 0!==aue[$.trim(a)]){var c=void 0===aue[$.trim(a)]?a:aue[$.trim(a)];b.style.display=c?"block":"none";d&&!b.hasAttribute("a-once")&&Aue.addMonitor(b,"show",{initialValue:a},$.trim(a))}};
Aue.setClass=function(b,a,d){var c=eval("("+a+")"),e;for(e in c){var f=aue[$.trim(c[e])];void 0!==f&&(f?$(b).addClass(e):$(b).removeClass(e),d&&!b.hasAttribute("a-once")&&Aue.addMonitor(b,"class",{initialValue:a},$.trim($.trim(c[e]))))}};Aue.setClick=function(b){var a=b.getAttribute("a-click");b.addEventListener("click",function(){try{eval("aueMethod."+(-1!=a.indexOf("(")?a:a+"(b)"))}catch(d){Aue.error(a+" is not a function")}})};
Aue.setFor=function(b,a,d,c,e){var f=d.substring(d.lastIndexOf("in")+2,d.length).trim(),k=d.substring(0,d.lastIndexOf("in")).trim();if(void 0!==aue[$.trim(f)]){a.innerHTML="";for(var h in aue[f]){var g=b.replace(/{{\s+index\s+}}/g,h);g=g.replace(new RegExp("{{\\s+"+k+"\\s+}}","g"),aue[f][h]);a.innerHTML+=g}a.innerHTML+=" ";Aue.loadEl(a);c&&!e&&Aue.addMonitor("","for",{rootHtml:b,parent:a,initialValue:d},$.trim(f))}};
Aue.setMonitor=function(b){var a=b;Object.defineProperty(aue,b,{get:function(){return b},set:function(d){b=d;d=$jscomp.makeIterator(modelTable);for(var c=d.next();!c.done;c=d.next()){c=c.value;var e=c.attribute,f=c.parameter;if(c.key===a)switch(e){case "model":Aue.setModel(c.child,f.variableName,!1)}}d=$jscomp.makeIterator(monitorTable);for(c=d.next();!c.done;c=d.next())if(c=c.value,e=c.attribute,f=c.parameter,c.key===a)switch(e){case "innerText":Aue.setInnerText(c.child,f.initialValue,!1);break;
case "value":Aue.setValue(c.child,f.initialValue,!1);break;case "checked":Aue.setChecked(c.child,f.initialValue,!1);break;case "show":Aue.setShow(c.child,f.initialValue,!1);break;case "class":Aue.setClass(c.child,f.initialValue,!1);break;case "for":Aue.setFor(f.rootHtml,f.parent,f.initialValue,!1)}}})};Aue.addModel=function(b,a,d,c){var e={};e.key=c;e.child=b;e.attribute=a;e.parameter=d;modelTable.push(e)};Aue.addMonitor=function(b,a,d,c){var e={};e.key=c;e.child=b;e.attribute=a;e.parameter=d;monitorTable.push(e)};
Aue.error=function(b){console.error("[Aue] "+b)};
